version: "3"
services:
  wiremock_demo:
    container_name: wiremock_demo
    image: rodolpheche/wiremock:2.25.1
#    networks:
#      - bridge
    environment:
      WIREMOCK_HOST_NAME: wiremock_host
#      MYSQL_ROOT_PASSWORD: hellokoding
#      MYSQL_ROOT_HOST: '%'
    volumes:
      - $PWD/product-api-mock:/home/wiremock
#    ports:
#      - "9090:8080"
    restart: always

  gateway:
    container_name: gateway
#    image: ebd622/gateway-docker
    build: ./gateway
#    networks:
#      - host
    links:
      - wiremock_demo:wiremock_host
    ports:
      - 8080:8080
    depends_on:
      - wiremock_demo
    restart: always
