version: "3"
services:
  wiremock_demo:
    container_name: wiremock_demo
    image: rodolpheche/wiremock:2.25.1
#    networks:
#      - bridge
    environment:
# --- WIREMOCK_HOST_NAME can be used in mock to define a host-name
      WIREMOCK_HOST_NAME: wiremock_host
    volumes:
      - $PWD/product-api-mock:/home/wiremock
    restart: always

  gateway:
    container_name: gateway
#   --- Use [image:] to create a container from an existing image
#    image: ebd622/gateway-docker
#   --- Use [build:] first to buid a new image and then (second) create a container
    build: ./gateway
    links:
      - wiremock_demo:wiremock_host
    ports:
      - 8080:8080
    depends_on:
      - wiremock_demo
    restart: always
