version: "3"
services:
  wiremock_demo:
    container_name: wiremock_demo
    image: rodolpheche/wiremock:2.25.1
#    networks:
#      - bridge
    environment:
      WIREMOCK_HOST_NAME: wiremock_host
    volumes:
      - $PWD/product-api-mock:/home/wiremock
#    ports:
#      - "9090:8080"
    restart: always

  gateway:
    container_name: gateway
#   --- Uncomment [image:] to use an existing image
#    image: ebd622/gateway-docker
#   --- Use [build:] to create an image
    build: ./gateway
    links:
      - wiremock_demo:wiremock_host
    ports:
      - 8080:8080
    depends_on:
      - wiremock_demo
    restart: always
