name: (CD) NodeJS with Webpack 

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        #node-version: ${{ matrix.node-version }}
        node-version: '20.x'

    - name: Build
      run: |
        npm install --prefix ./express-api/

    - name: Use secret
      run: echo ${{ secrets.WEB_APP_API_TOKEN }}

    - name: Configure Git
      run: |
        git config --global user.email "eburdo@gmail.com"
        git config --global user.name "Eugeny"

    - name: Clone winkel-app-api repo
      run: |
        echo "Current path:" 
        pwd
        git clone https://${{ secrets.WEB_APP_API_TOKEN }}@api.glitch.com/git/winkel-app-api
        cd winkel-app-api
        echo 'List a folder:'
        ls -l
        cat package.json
        #rm TODO.md
        #git add .
        #git commit -m "Update from source repo"
        #git push origin main

    - name: Run Glitch-git status
      id: git-status
      run: |
        cd winkel-app-api
        touch readme.tmp
        ls -l
        pwd
        #STATUS=$(git status --porcelain)
        #echo "status=$STATUS" >> $GITHUB_OUTPUT
        {
          echo 'STATUS<<EOF'
          git status --porcelain
          echo EOF
        } >> $GITHUB_OUTPUT
        
    - name: Step A
      if: steps.git-status.outputs.status != ''
      run: |
        echo "There are uncommitted changes. Running Step A..."
        # Add commands for Step A here

    - name: Step B
      if: steps.git-status.outputs.status == ''
      run: |
        echo "No uncommitted changes. Running Step B..."
        # Add commands for Step B here

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Build
      run: |
        npm install --prefix ./express-api/
        pwd
        ls -l
