name: (CD) NodeJS with Webpack 

on:
  push:
    branches: [ "main" ]

jobs:

  check_changes:
    runs-on: ubuntu-latest
    outputs:
      #[status_result] is used to keep a result of "git status"
      status_result: ${{ steps.git-status.outputs.status_result }}


    steps:
    - uses: actions/checkout@v4

    - name: Configure Git
      run: |
        git config --global user.email "eburdo@gmail.com"
        git config --global user.name "Eugeny"

    - name: Clone winkel-app-api repo
      run: |
        echo "Current path:" 
        pwd
        cd express-api
        echo "cd express-api" 
        pwd
        git clone https://${{ secrets.WEB_APP_API_TOKEN }}@api.glitch.com/git/winkel-app-api

        ## Copy current version into [winkel-app-api] git-project
        cp products-api.js winkel-app-api/server.js

        # Remove and copy data/
        rm winkel-app-api/data/*
        cp data/* winkel-app-api/data
        
        echo "ls -l winkel-app-api" 
        ls -l winkel-app-api

    - name: Check Glitch-git status
      id: git-status
      run: |
        pwd
        ls -l
        cd express-api/winkel-app-api
        #touch readme.tmp
        ls -l
        pwd
        echo 'Run git-status:'
        git status --porcelain
        {
          echo 'status_result<<EOF'
          git status --porcelain
          echo EOF
        } >> $GITHUB_OUTPUT
        
  build:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.status_result != ''
    steps:
      - name: Run build
        run: echo "Running Job build"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy
        run: echo "Running Job deploy"

  skip:
    needs: check_changes
    runs-on: ubuntu-latest
    if: needs.check_changes.outputs.status_result == ''
    steps:
      - name: skip deployment
        run: |
          echo "No changes, skip depoyment"
          pwd
          ls -l
        
