name: (CD) NodeJS with Webpack 

on:
  push:
    branches: [ "main" ]

jobs:

  check_status:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Configure Git
      run: |
        git config --global user.email "eburdo@gmail.com"
        git config --global user.name "Eugeny"

    - name: Clone winkel-app-api repo
      run: |
        echo "Current path:" 
        pwd
        git clone https://${{ secrets.WEB_APP_API_TOKEN }}@api.glitch.com/git/winkel-app-api
        cd winkel-app-api
        echo 'List a folder:'
        ls -l
        cat package.json
        #rm TODO.md
        #git add .
        #git commit -m "Update from source repo"
        #git push origin main

    - name: Check Glitch-git status
      id: git-status
      run: |
        cd winkel-app-api
        touch readme.tmp
        ls -l
        pwd
        #STATUS=$(git status --porcelain)
        #echo "status=$STATUS" >> $GITHUB_OUTPUT
        {
          echo 'STATUS<<EOF'
          git status --porcelain
          echo EOF
        } >> $GITHUB_OUTPUT
        
  deploy:
    needs: check_status
    runs-on: ubuntu-latest
    if: needs.check_status.git-status.outputs.status != ''

    steps:
      - name: Run Job A tasks
        run: echo "Running Job A"

  skip:
    needs: check_status
    runs-on: ubuntu-latest
    if: needs.check_status.git-status.outputs.status == ''

    steps:
      - name: Run Job B tasks
        run: echo "Running Job B"
        


